services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - project.env

  db:
    container_name: postgresql_database
    image: postgres:16.1
    restart: unless-stopped
    env_file:
      - project.env
  
  db-migrations:
    image: flyway/flyway:10.0.0-alpine
    env_file:
      - project.env
    depends_on:
      - db
    volumes:
      - ./flyway/sql:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate


