services:
  web-app:
    build:
      context: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    depends_on:
      - web-db
    env_file:
      - project.env

  web-db:
    container_name: postgresql_database
    image: postgres:16.1
    restart: unless-stopped
    env_file:
      - project.env
  
  web-db-migrations:
    image: flyway/flyway:11.5.0-alpine
    env_file:
      - project.env
    depends_on:
      - web-db
    volumes:
      - ./flyway/sql:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate


