// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.flyway_schema_history */
export type FlywaySchemaHistoryInstalledRank = number & { __brand: 'FlywaySchemaHistoryInstalledRank' };

/** Represents the table public.flyway_schema_history */
export default interface FlywaySchemaHistoryTable {
  installed_rank: ColumnType<FlywaySchemaHistoryInstalledRank, FlywaySchemaHistoryInstalledRank, FlywaySchemaHistoryInstalledRank>;

  version: ColumnType<string | null, string | null, string | null>;

  description: ColumnType<string, string, string>;

  type: ColumnType<string, string, string>;

  script: ColumnType<string, string, string>;

  checksum: ColumnType<number | null, number | null, number | null>;

  installed_by: ColumnType<string, string, string>;

  installed_on: ColumnType<Date, Date | string | undefined, Date | string>;

  execution_time: ColumnType<number, number, number>;

  success: ColumnType<boolean, boolean, boolean>;
}

export type FlywaySchemaHistory = Selectable<FlywaySchemaHistoryTable>;

export type NewFlywaySchemaHistory = Insertable<FlywaySchemaHistoryTable>;

export type FlywaySchemaHistoryUpdate = Updateable<FlywaySchemaHistoryTable>;
