// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as VerificationTable } from './Verification';
import type { default as AccountTable } from './Account';
import type { default as AppUserTable } from './AppUser';
import type { default as SessionTable } from './Session';
import type { default as FlywaySchemaHistoryTable } from './FlywaySchemaHistory';

export default interface PublicSchema {
  verification: VerificationTable;

  account: AccountTable;

  app_user: AppUserTable;

  session: SessionTable;

  flyway_schema_history: FlywaySchemaHistoryTable;
}
