// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { AppUserId } from './AppUser';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.session */
export type SessionId = string & { __brand: 'SessionId' };

/** Represents the table public.session */
export default interface SessionTable {
  id: ColumnType<SessionId, SessionId, SessionId>;

  userId: ColumnType<AppUserId, AppUserId, AppUserId>;

  token: ColumnType<string, string, string>;

  expiresAt: ColumnType<Date, Date | string, Date | string>;

  ipAddress: ColumnType<string | null, string | null, string | null>;

  userAgent: ColumnType<string | null, string | null, string | null>;

  createdAt: ColumnType<Date, Date | string, Date | string>;

  updatedAt: ColumnType<Date, Date | string, Date | string>;
}

export type Session = Selectable<SessionTable>;

export type NewSession = Insertable<SessionTable>;

export type SessionUpdate = Updateable<SessionTable>;
